name: Sync Notion to GitHub

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Convert Notion Database to Markdown
        uses: ega4432/notion-to-markdown-action@v0
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        with:
          output_path: 'posts'
          filename_property: 'Title'
	  download_images: true          # Tells the action to download images from Notion
          images_path: 'static/images'   # Downloads them directly into Hugo's asset folder

      - name: Commit and Push to Repository
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add .
          git diff-index --quiet HEAD || (git commit -m "Automated sync from Notion" && git push)
